services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    image: dl-dev
    container_name: dl-dev
    working_dir: /workspace
    environment:
      - LOCAL_UID=${CURRENT_UID}
    volumes:
      - ./src:/workspace/src
      - ./results:/workspace/results
      - ./models:/workspace/models
      - ./data:/workspace/data
      - ./cache:/workspace/cache
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  # IGNORE FOR NON NIXOS USERS
  python-nx:
    build:
      context: .
      dockerfile: Dockerfile
    image: dl-dev
    container_name: dl-dev
    working_dir: /workspace
    environment:
      - LOCAL_UID=${CURRENT_UID}
    volumes:
      - ./src:/workspace/src
      - ./results:/workspace/results
      - ./models:/workspace/models
      - ./data:/workspace/data
      - ./cache:/workspace/cache
    stdin_open: true
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: cdi
              device_ids:
                - nvidia.com/gpu=all
              capabilities: [ gpu ]